### ISSUE TITLE
Merge with poomas?

### ISSUE THREAD

**Issue by marmistrz** [lelandjansen/did-it-run#29]
It appears that I have once written quite a similar application, called [poomas](https://github.com/marmistrz/poomas). We may consider merging them.

The example e-mail sent by my app looks like this:
```
Command: ./run.sh 2 2 60000 10
Execution time: 666.218 s
Exit code: 0
Job name: gamelife-test
```
The extra features it has:
* support for job names
* maintaining a simple, toml-based database with all the jobs executed.

On the other hand, your app seems somewhat more user-friendly (better handling of configuration) and has much better test coverage.

**Comment by lelandjansen** [comment]
Hi @marmistrz, neat project (great minds think alike 😜)! I like your idea to maintain a local job history database.

Did it Run? is in the early stages of development and I have a laundry list of features I’d still like to implement including [desktop notifications](https://github.com/lelandjansen/did-it-run/pull/24), storing credentials in the keychain, and integrating with a backend to support features like console output streaming and and push notifications.

Merging our programs is an interesting idea. I’d certainly be open to a pull request if there’s a feature you’d like to see in Did it Run?. Please let me know if you’re interested to contribute and I’ll get together some contribution guidelines (so there’s less surprises in code review).

**Comment by marmistrz** [comment]
This sounds like a good idea.
What do you mean by push notifications? An Android application using GCM?

**Comment by lelandjansen** [comment]
> What do you mean by push notifications? An Android application using GCM?

Yes. As you predicted, native iOS and Android applications that support job monitoring (e.g. console output streaming) and can send push notifications. I'll likely use [Azure Notification Hubs](https://azure.microsoft.com/en-ca/services/notification-hubs/), a similar service.

**Comment by lelandjansen** [comment]
Closing since this issue has been inactive for a week.

@marmistrz Feel free to reopen this issue if you feel it is still unresolved.

**Comment by marmistrz** [comment]
Sorry for the delay, I've been quity busy lately.

Azure Notification Hubs seems to use FCM to deliver messages, which is proprietary. This will prevent the app from being accepted into F-Droid, the catalog of open-source applications. On the other hand, if the app has a fallback, FOSS backend (e.g. long polling, web sockets or TCP push) and has a FOSS-only build flavor, I'd have nothing against that idea.

**Comment by lelandjansen** [comment]
> This will prevent the app from being accepted into F-Droid, the catalog of open-source applications.

Interesting idea. I've never heard of F-Droid. What's wrong with the Play Store? The app can still be open source, and FCM seems to be the standard on Android.

> On the other hand, if the app has a fallback, FOSS backend...

My intention was for the Did it Run? backend to be closed-source. Will this disqualify the app from F-Droid anyway?

Rationale: The backend is where most of my expenses will lie and I might choose to add a paid feature to help me cover the infrastructure costs. For example, using SendGrid (or a similar service) to deliver email notifications (in lieu of manually configuring SMTP credentials). For this reason I'm keeping the backend closed-source (at least for now).

**Comment by marmistrz** [comment]
> Interesting idea. I've never heard of F-Droid. What's wrong with the Play Store? The app can still be open source, and FCM seems to be the standard on Android.
If the hardware vendor wants to support FCM, [he is effectively prohibited to build non-Google-approved devices](https://arstechnica.com/gadgets/2018/07/googles-iron-grip-on-android-controlling-open-source-by-any-means-necessary/). Besides, some users don't install GMS (Google Mobile Services) on their LineageOS-powered devices for privacy reasons. It's also against the terms & conditions to access Play Store in any other way than through the official Google Play app (which is a part of GMS). 

> My intention was for the Did it Run? backend to be closed-source. Will this disqualify the app from F-Droid anyway?

No, but it will be displayed as an anti-feature. The server-side may be open-source, but the client-side may have no closed-source dependencies.

> Rationale: The backend is where most of my expenses will lie and I might choose to add a paid feature to help me cover the infrastructure costs. For example, using SendGrid (or a similar service) to deliver email notifications (in lieu of manually configuring SMTP credentials). For this reason I'm keeping the backend closed-source (at least for now).

You can always keep your API keys private, so that everyone can easily self-host the backend and connect to their own server instead.
